spring.application.name=careertrack-be
server.port=8081
#  Veritaban? Yolun (Postgres varsay?lan olarak 5432 portunu kullan?r)
spring.datasource.url=jdbc:postgresql://localhost:5432/careertrack
spring.datasource.username=seyran
spring.datasource.password=seyran2310
#  Hibernate Sihri (Biz Java'da kod yazd?kça o tablolar? otomatik günceller)
spring.jpa.hibernate.ddl-auto=update
#  Konsolda yap?lan SQL i?lemlerini görmek için (Hata ay?klarken çok i?e yarar)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true